### ISSUE TITLE
Pushing a manifest list from a layout fails with unexpected media type

### ISSUE THREAD

**Issue by glyn** [pivotal/image-relocation#34]
This can be reproduced as follows:
```
$ irel layout add scratch/layout busybox:1.28
added docker.io/library/busybox:1.28 with digest sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47 to OCI image layout at scratch/layout
$ irel layout push scratch/layout sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47 glyn/busyboxcopy:1@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
2019/09/19 10:59:42 push failed: unexpected media type for sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47: application/vnd.docker.distribution.manifest.list.v2+json
```

**Comment by vdice** [comment]
We've reproduced this error, albeit at a higher-level: When (re-)publishing a bundle via [Porter](https://github.com/deislabs/porter) via use of this library.

Coincidentally, the sole application image of an example [bundle](https://github.com/deislabs/porter/blob/94a81861c2826cd7c921c8a03e0c32b8c19faa32/tests/testdata/bundles/porter-busybox/porter.yaml) that hit this issue was `busybox`, as used in the description above.  When the bundle is supplied in the form of an archive, Porter extracts this archive and uses this library's OCI Layout parsing functionality to parse and push the image(s) with updated image name(s).

In doing so, we encountered the same `unexpected mediat type` error above.  Use of another library image, `alpine` resulted in the same, leading me to believe it may center around DockerHub library images and their use of this "unexpected" media type (`application/vnd.docker.distribution.manifest.list.v2+json`)?

The two relevant methods in the [google/go-containerregistry](https://github.com/google/go-containerregistry) library that this repo uses appear to be `Image(h v1.Hash)` and `ImageIndex(h v1.Hash)` as seen [here](https://github.com/google/go-containerregistry/blob/master/pkg/v1/layout/index.go#L81-L119).  No doubt @glyn is already very familiar with these :)  I'm still very new to this code, but it appears with the example of this library `busybox` image, we may need to utilize the latter `ImageIndex` variant and yet somehow still end up with an actual image in the end (as opposed to an imageIndex) for pushing.

For the aforementioned example bundle, we've switched to use of a re-tagged `busybox` image in a repo we own (`deislabs/busybox`) which avoids this error.  However, it would be preferable to support republishing all types of images in a bundle, hence interest in this issue and hopefully eventual fix!

**Comment by glyn** [comment]
https://github.com/google/go-containerregistry/pull/570 needs to land as part of the fix.

**Comment by glyn** [comment]
> I'm still very new to this code, but it appears with the example of this library `busybox` image, we may need to utilize the latter `ImageIndex(..)` variant and yet somehow still end up with an actual image in the end (as opposed to an imageIndex) for pushing.

We actually want to end up pushing an image index. I'll push a draft fix soon.

**Comment by vdice** [comment]
Thanks @glyn !  The Draft PR looks great; I had done a similar mod and also ran into the `push failed: MANIFEST_INVALID: manifest invalid; map[]` issue and that's where I stopped.  Appreciate your persistence in filing the upstream issue.
